#!/bin/bash
#
# ./display-httpd-status
# 
# Andres Hernandez - tonejito
# Display Apache HTTPD status using mod_status and links
# Released under the BSD License

for bin in which links grep tee
do
  if [ ! -x "`which $bin`" ]
  then
    exit 1
  fi
done

links -dump 'http://localhost/server-status' | \
grep -v 'OPTIONS \* HTTP/1.0' | \
tee httpd.status
