#!/bin/bash
#
# ./display-httpd-config
# 
# Andres Hernandez - tonejito
# Display Apache HTTPD loaded config using mod_info and links
# Released under the BSD License

for bin in which echo links sed tee
do
  if [ ! -x "`which $bin`" ]
  then
    exit 1
  fi
done

# Send all of this output through the pipe
(
  echo "# vim: syntax=apache sr noet hlsearch"
  links -dump -width 256 'http://localhost/server-info?config'
) | \
sed -f ./display-httpd-config.sed | \
tee httpd.config
